name: Build Ren'Py VN

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Build VN project
        uses: ProjectAliceDev/renpy-build-action@master
        with:
          sdk-version: '8.1.3'  # Ren'Py 8.1.3（稳定版，支持 Python 3）
          project-dir: '.'  # 项目根目录（game 文件夹在里面）
        env:
          SDL_AUDIODRIVER: dummy
          SDL_VIDEODRIVER: dummy
          RENPY_RENDERER: sw  # 使用软件渲染器，避免 OpenGL 错误
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: renpy-builds
          path: |
            *.zip
            *.tar.bz2
          if-no-files-found: warn