name: Build Ren'Py VN

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Cache Ren'Py SDK
        uses: actions/cache@v4
        with:
          path: renpy-sdk
          key: renpy-8.1.3-sdk
      
      - name: Download Ren'Py SDK
        run: |
          if [ ! -d "renpy-sdk" ]; then
            wget https://www.renpy.org/dl/8.1.3/renpy-8.1.3-sdk.tar.bz2
            tar xf renpy-8.1.3-sdk.tar.bz2
            mv renpy-8.1.3-sdk renpy-sdk
          fi
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
      
      - name: Build Distributions
        run: |
          export RENPY_RENDERER=sw
          export SDL_AUDIODRIVER=dummy
          export SDL_VIDEODRIVER=dummy
          cd renpy-sdk
          # 使用虚拟显示器运行构建 - 打包 Web, Linux, Windows
          xvfb-run -a ./renpy.sh launcher distribute ../. --package web --package linux --package pc
      
      - name: List Generated Files
        run: |
          ls -la *.zip *.tar.bz2 || echo "No build files found"
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: renpy-builds
          path: |
            *.zip
            *.tar.bz2
          if-no-files-found: warn