name: Build Ren'Py VN

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Build VN project
        uses: ProjectAliceDev/renpy-build-action@master
        with:
          sdk-version: '8.1.3'  # Ren'Py 8.1.3（稳定版，支持 Python 3）
          project-dir: './game'
        #   package: 'web'  # 打包为 Web 平台（可选: pc, mac, linux, web, android, ios, all）
        env:
          SDL_AUDIODRIVER: dummy
          SDL_VIDEODRIVER: dummy
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: renpy-web-build
          path: game/*.zip  # Web 构建输出